name: Scheduled site

on:
  workflow_dispatch:

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Salin site.txt baru ke root
        run: |
          cp update_staged/site.txt site.txt
          git config user.name "botdoh"
          git config user.email "kraytahalu@gmail.com"
          git add site.txt
          git commit -m "Scheduled update for site.txt at 23:00 WIB"
          git push origin main
